<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Projeto_Integrador2</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <Compile Remove="metodologias-ageis\**" />
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="tests\**" />
    <EmbeddedResource Remove="metodologias-ageis\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="tests\**" />
    <None Remove="metodologias-ageis\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
  </ItemGroup>

</Project>
